import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
matches = pd.read_csv("C:\\Users\\Lakshman\\OneDrive\\ipl_matches_200.csv")
#print(matches)
# 1. OVERVIEW OF THE IPL_MATCHES_TABLE
#print("==========================================================OVERVIEW OF THE MATCHES===============================================")
#print(matches.head(10))
#print("============================== information========================")
#print(matches.info())
# 2. CHECK MISSNG VALUES IN MATCHES
#print("===========================================================CHECK MISSNG VALUES IN MATCHES=====================================")
missing_values=matches.isnull().sum()
print(missing_values)
# 3. Matches Per Season represented n bar graph
season_count = matches['season'].value_counts().sort_index()
plt.figure(figsize=(10,5))
plt.bar(season_count.index, season_count.values)
plt.title("Matches Per Season")
plt.xlabel("Season")
plt.ylabel("Matches")
plt.xticks(rotation=45)
plt.show()
# 4. Most Successful Team
team_wins = matches['winner'].value_counts()
plt.figure(figsize=(12,5))
plt.bar(team_wins.index, team_wins.values)
plt.title("Most Successful IPL Teams")
plt.ylabel("Wins")
plt.xticks(rotation=60)
plt.show()
# 5. Toss Decision Analysis
toss_decision = matches['toss_decision'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(toss_decision.values, labels=toss_decision.index, autopct='%1.1f%%')
plt.title("Toss Decision")
plt.show()
# 6. Top 10 Man of the Match Winners
mom = matches['player_of_match'].value_counts().head(10)
plt.figure(figsize=(10,5))
plt.barh(mom.index, mom.values)
plt.title("Top 10 Man of the Match Winners")
plt.xlabel("Awards")
plt.gca().invert_yaxis()
plt.show()
#7. Distribution of Runs Per Ball
deliveries= pd.read_csv("C:\\Users\\Lakshman\\Downloads\\ipl_deliveries_10000.csv")
plt.figure(figsize=(10,5))
plt.hist(deliveries['total_runs'], bins=30)
plt.title("Distribution of Runs Per Ball")
plt.xlabel("Runs")
plt.ylabel("Frequency")
plt.show()
# 8. Top 10 Run Scorers
batsman_runs = deliveries.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,5))
plt.barh(batsman_runs.index, batsman_runs.values,color='b')
plt.title("Top 10 Batsmen by Runs")
plt.xlabel("Runs Scored")
plt.gca().invert_yaxis()
plt.show()
# 9. Boundary Hitters
boundaries = deliveries[deliveries['batsman_runs'] >= 4]
boundary_count = boundaries['batsman'].value_counts().head(10)
plt.figure(figsize=(10,5))
plt.barh(boundary_count.index, boundary_count.values,color='orange')
plt.title("Top Boundary Hitters")
plt.xlabel("Boundaries")
plt.gca().invert_yaxis()
plt.show()
# 10.  Most Wickets by Bowlers
wickets = deliveries[deliveries['dismissal_kind'].notnull()]
bowler_wickets = wickets['bowler'].value_counts().head(10)
plt.figure(figsize=(10,5))
plt.plot(bowler_wickets.index, bowler_wickets.values,color='green')
plt.title("Top Wicket Takers")
plt.xlabel("Wickets")
plt.gca().invert_yaxis()
plt.show()
#  11. Win by Runs
plt.figure(figsize=(10,5))
plt.hist(matches['win_by_runs'], bins=30,color='cyan')
plt.title("Win by Runs Distribution")
plt.xlabel("Runs")
plt.ylabel("Frequency")
plt.show()
# 12. Win by Wickets
plt.figure(figsize=(10,5))
plt.hist(matches['win_by_wickets'], bins=30,color='yellow')
plt.title("Win by Wickets Distribution")
plt.xlabel("Wickets")
plt.ylabel("Frequency")
plt.show()
# 13. Teams Winning the Most Tosses
toss_wins = matches['toss_winner'].value_counts()
plt.figure(figsize=(12,5))
plt.bar(toss_wins.index, toss_wins.values)
plt.title("Teams Winning the Most Tosses")
plt.xticks(rotation=90)
plt.ylabel("Toss Wins")
plt.show()
